### ISSUE TITLE
RHEL - Equibvalent distribution for use in ansible project and collection

### ISSUE THREAD

**Issue by JackTrue** [nginxinc/ansible-collection-nginx#6]
### Is your feature request related to a problem? Please describe

I'm using a lot RHEL and Centos distribution, Now with Centos "stream" moving from v.8 distribution i'm interested in using Rocky Linux.

### Describe the solution you'd like

Extend "limitation" in use only whit distribution indicated in vars/main.yml also with Rocky linux distribution
 
### Describe alternatives you've considered

change the following variable available from

```
nginx_distributions: [
  'Alpine', 'Amazon', 'CentOS', 'Debian', 'FreeBSD', 'RedHat', 'SLES', 'Ubuntu',
  'NetBSD', 'OpenBSD', 'DragonFlyBSD', 'HardenedBSD',
]
```

--- to ---

```
nginx_distributions: [
  'Alpine', 'Amazon', 'CentOS', 'Debian', 'FreeBSD', 'RedHat', 'SLES', 'Ubuntu',
  'NetBSD', 'OpenBSD', 'DragonFlyBSD', 'HardenedBSD', 'Rocky',
]
```

### Additional context
The preliminary test can be done correct and installation can be made.

##Add any other context or screenshots about the feature request here.
Tested proficiency with Rocky Linux 8.5 version using the following play:
######
```
---
- name: install and starts the Nginx web server on server one 
  hosts: one
  pre_tasks:
  - name: ensure http is not installed
    yum:
      name: httpd
      state: absent

  collections:
    - nginxinc.nginx_core
  roles:
    - role: nginx
...

```
######
